### ISSUE TITLE
Roadmap for version 1.0.0

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-js-typed-array#4]
- [x] Write the roadmap xb
 - [x] Complete tests
   - [x] Dedicated creation (`JsUint8Array`, ...) modules
   - [x] `JsTypedArray` module
 - [x] Complete functions
   - [x] Write the `fromArray` function
   - [x] Write a `fromTypedArray` function to be able to convert typed arrays
   - [x] Write `toList` and `toArray` functions
   - [x] Write encoders and decoders
   - [x] Write a comparison function to check if two arrays are equal
   - [x] Write non indexed functions (all, any, filter, map, map2, foldl, foldr, foldl2, foldr2)
 - [x] Remove incompatible functions (fill, join, slice)
 - [x] Write benchmarks comparing with other data structures (List, Array, TypedArray). Use exponential scales (10 - 100 - ...) to test different use cases.
   - *Array Creation*
   - [x] Creation of an array of 0 from scratch
   - [x] Creation of a constant array
   - [x] Initialization of array with function
   - *Basic requests*
   - [x] Get the length
   - [x] Get value at half size
   - *Predicates*
   - [x] All
   - [x] Any
   - [x] Filter
   - *Array comparison*
   - [x] Equal
   - *Array extraction and appending*
   - [x] Slice
   - [x] Append two arrays
   - *Array transformations*
   - [x] Replace a value at half size
   - [x] Map
   - *Array reductions*
   - [x] Fold left
   - [x] Fold right
 - [ ] Continue development of [elm-tensor] as proof of concept
 - [ ] Add the DataView API
 - [ ] Change few things in the API:
    - [ ] Move types in a `Typed` module? (not sure useful)
    - [ ] Create a `RangeError` that would be returned on impossible operations on buffers
    - [ ] Use a `Result` instead of `Maybe` for the `fromValue` functions
 - [ ] Implementing example use cases (issue #7)
 - [x] Make a post on Discourse
 - [ ] Change with feedback
 - [ ] Write medium article
 - [ ] tag version 1.0.0

[elm-tensor]: https://github.com/mpizenberg/elm-tensor

**Comment by mpizenberg** [comment]
Documentation at commit 2573a08: [doc-2573a08.txt](https://github.com/mpizenberg/elm-js-typed-array/files/1609587/doc-2573a08.txt)

**Comment by mpizenberg** [comment]
Documentation at commit 1accc47: [doc-1accc47.txt](https://github.com/mpizenberg/elm-js-typed-array/files/1692923/doc-1accc47.txt)
